### PR TITLE
Include SSOWAT user panel.

### PR DESCRIPTION
**Pull request by opi**

### CODE REVIEW

**Comment by opi** [comment]
Doesn't seem to work on my Jirafeau installation

**Comment by opi** [comment]
SSOWat Subfilter that add ynhpanel.js does not work with `application/xhtml+xml; charset=utf-8` content type (See https://github.com/julienmalik/jirafeau_ynh/blob/master/sources/lib/template/header.php#L7 )

I don't know if we could patch Jirafeau sources or if the issue can be fixed through SSOWat

**Comment by opi** [comment]
Found it : sub_filter directive only applies to `text/html` content types by default, see http://nginx.org/en/docs/http/ngx_http_sub_module.html#sub_filter_types

Issue is know YunoHost related, but maybe I will open an issue for Jirafeau upstream so serve html (and HTML5) by default.

**Comment by julienmalik** [comment]
yep the jirafeau dev is currently quite reactive so it's a good idea ! thanks for the investigation

**Comment by opi** [comment]
But the patch provided here is still relevant, isn't it ? I guess you could merge it anyway ;)

**Pull request merged**
